### ISSUE TITLE
Interactive Learning Research

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#1]
Please start researching different examples of interactive learning and post them here. Some questions that can help you get started:

- What are some other terms for "interactive learning"? (eg. engagement activities)
- Are there other companies that make interactive learning software?
- Are there existing javascript libraries or github repositories?
- What sort of activities would be considered interactive learning?

Keep in mind that you may find examples that **do not** use software. That could be an opportunity for us to make something new!

**Comment by Raunaq27** [comment]
I am putting the research I find in a word doc that I will share

**Comment by Raunaq27** [comment]
[Research.pdf](https://github.com/Interactive-Design-and-Technology/interactive-learning/files/11097271/Research.pdf)

**Comment by Raunaq27** [comment]
Added the research that I found useful

**Comment by Anmol135** [comment]
[Research.pdf](https://github.com/Interactive-Design-and-Technology/interactive-learning/files/11103326/Research.pdf)

**Comment by Anmol135** [comment]
This is the research I found!

**Comment by FeXd** [comment]
Thanks for the research reports! As discussed in today's meeting, please in the future share live documents for this sort of thing. Could be a word doc or jam board, but sharing so that others can hop in to see changes as you work is very helpful.

Some feedback regarding your reports:
- generally, please give us MORE, not just titles and links
- this means, SUMMARIZE the information (if you only post links and titles, now I have to read it and summarize myself, which defeats the purpose)
- add images, visualization, bullets, writeups, etc. whatever helps get the point across as to what it is
- consider making comparison tables to compare different sites or solutions you find
- NOTE: you do not have to dive deep into EVERYTHING you find, only those that have POTENTIAL
