### ISSUE TITLE
Drag and drop Interactive JavaScript

### ISSUE THREAD

**Issue by Raunaq27** [Interactive-Design-and-Technology/interactive-learning#10]
Create a simple webpage using basic HTML, CSS, and JavaScript, that allows us to have a "Drag and Drop" activity.

Example of existing activities are available in /source directory, specifically:

- Interactive Drag and Drop Activity Template 

Adobe Captivate also has some cool examples of "Drag and Drop" activities which could be incorporated: https://www.adobe.com/ca/products/captivate.html

Please refer to #1 and #2 for more examples.

## Implementation
- please make your files inside a folder directly in the root of the project, for example `drag-and-drop`
- inside should only be three files, `index.html`, `script.js`, `style.css`
- we are trying to create these examples as simply as possible, with **vanilla JavaScript** where possible (no 3rd party libraries)
- it is possible that a 3rd party library _may_ be required, but please check in before you attempt to implement
- feel free to use the /source examples as a base for your implementation, **but** we **do not** want to be using `jquery`

## Expectations
- there is no specific deadline for this task
- it is expected that you will check in daily on progress
- you should make a new branch on git and **push your branch regularly**
- when you are done, or when you want feedback, please open a pull request and let the team know

**Comment by Anmol135** [comment]
Tried a bunch of coding for the drag and drop but did not work out.
Starting over fresh now.

**Comment by Anmol135** [comment]
This is the wireframe that I would aim towards achieving.

**Comment by Anmol135** [comment]
![Image](https://user-images.githubusercontent.com/121471316/232599874-ba24f756-b349-42bb-9da4-9d1541bbf984.png)

**Comment by Anmol135** [comment]
I am working on a branch called "anmol_drag_and_drop". Feel free to check it out.
