### ISSUE TITLE
Generate Questions JSON from Form

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#16]
Create a simple webpage using basic HTML, CSS, and JavaScript, that has a `<form>` and allows users to create `JSON` that have questions and answers, similar to the JavaScript Objects that we are using in interactive learning JavaScript thus far.

Users should be able to add and remove questions from a form interactively, and then when they are finished, they click a Submit button, which generates the JSON and outputs it to the screen.

## Implementation
- please make your files inside a folder directly in the root of the project, for example `drag-and-drop`
- inside should only be three files, `index.html`, `script.js`, `style.css`
- we are trying to create these examples as simply as possible, with **vanilla JavaScript** where possible (no 3rd party libraries)
- it is possible that a 3rd party library _may_ be required, but please check in before you attempt to implement
- feel free to use the /source examples as a base for your implementation, **but** we **do not** want to be using `jquery`

## Expectations
- there is no specific deadline for this task
- it is expected that you will check in daily on progress
- you should make a new branch on git and **push your branch regularly**
- when you are done, or when you want feedback, please open a pull request and let the team know

**Comment by Raunaq27** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/FormData

**Comment by FeXd** [comment]
I think using `FormData` would be possible, but am thinking we should just stay with basic DOM Manipulation via creating our own DOM tree: https://developer.mozilla.org/en-US/docs/Web/API/Document_object_model/How_to_create_a_DOM_tree

**Comment by Raunaq27** [comment]
## made a basic wireframe for how the form would look 

![Image](https://user-images.githubusercontent.com/121897309/231271253-ac4f8a6f-43ab-4c26-8950-62f526bd16af.jpg)

**Comment by Raunaq27** [comment]
Made a mockup

**Comment by FeXd** [comment]
Wireframe looks good. Mockup is ok, but I'd consider just using default styling of the browser for now. Just a regular looking form.

**Comment by Raunaq27** [comment]
#Added the feedback to the page

![Image](https://user-images.githubusercontent.com/121897309/232185461-a9df8f3c-f504-44ab-b6c6-030a261d87cf.png)

**Comment by FeXd** [comment]
Merged with #21
