### ISSUE TITLE
Term in Category

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#18]
Create a simple webpage using basic HTML, CSS, and JavaScript, that allows us to have a "Term in Category" activity.

Example of existing activities are available in /source directory, specifically:

- Interactive Term in Correct Category Template

Please refer to #1 and #2 for more examples.

## Implementation
- please make your files inside a folder directly in the root of the project, for example `drag-and-drop`
- inside should only be three files, `index.html`, `script.js`, `style.css`
- we are trying to create these examples as simply as possible, with **vanilla JavaScript** where possible (no 3rd party libraries)
- it is possible that a 3rd party library _may_ be required, but please check in before you attempt to implement
- feel free to use the /source examples as a base for your implementation, **but** we **do not** want to be using `jquery`

## Expectations
- there is no specific deadline for this task
- it is expected that you will check in daily on progress
- you should make a new branch on git and **push your branch regularly**
- when you are done, or when you want feedback, please open a pull request and let the team know

**Comment by FeXd** [comment]
Note that this story should be done **after** #10 since likely it will use the same techniques.

**Comment by Anmol135** [comment]
I have started working on it. To check out my work please visit branch [anmol_term_in_category](https://github.com/Interactive-Design-and-Technology/interactive-learning/tree/anmol_term_in_category).

**Comment by Anmol135** [comment]
The overall output, for now, looks somewhat like this.


![Image](https://user-images.githubusercontent.com/121471316/233400753-3d0edc02-649a-4a2f-aadc-745ea7f49d16.png)
