### ISSUE TITLE
Interactive Learning Brainstorm

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#2]
What sort of activities could we make interactive? Currently we have some old interactive activities built including:

- case study
- drag and drop
- expandable content
- fill in the blanks
- flash cards
- category sorting

Please post ideas here. Feel free to use mind maps, jam boards, or whatever might facilitate this.

**Comment by Raunaq27** [comment]
https://jamboard.google.com/d/1r-V2H2yns9r6NXKY-esBusnoVyU_AwkEuzRAtAqUxdQ/edit?usp=sharing

Jam Board for brainstorming

**Comment by Raunaq27** [comment]
Added a few ideas to the jam board, feel free to have a look at some and add your own

**Comment by Anmol135** [comment]
Just added a few more ideas on the board.

**Comment by Anmol135** [comment]
🤔💻 Having a hard time imagining how I would bring these ideas to life with javascript.🤔

**Comment by FeXd** [comment]
## Brainstorming Summary

Below is a summary of the brainstorming document, along with screenshots for keeping in the future.

- click to reveal
- drag and drop
- crossword
- stories (character dialogue, 3d ebook)
- quizzes and assessments
- million dollar (similar to who wants to be a millionare)
- games (tic-tac-toe)



![Image](https://user-images.githubusercontent.com/553767/229196640-f6659cbe-d695-4f24-a338-c24e73371e7b.png)
![Image](https://user-images.githubusercontent.com/553767/229196638-520c065b-0947-4527-9c92-394934b3c4ad.png)
![Image](https://user-images.githubusercontent.com/553767/229196641-146ba5d5-8dc5-466d-9fb1-892af731fbdb.png)
![Image](https://user-images.githubusercontent.com/553767/229196637-de12de0e-d5c9-4ac8-b4e4-6c43e4484501.png)
![Image](https://user-images.githubusercontent.com/553767/229196639-6f76b9c5-4022-4717-9210-2a93016b0a6b.png)
![Image](https://user-images.githubusercontent.com/553767/229196636-5ef5d1f4-6418-4b09-b6de-700e8d39ed07.png)
![Image](https://user-images.githubusercontent.com/553767/229196635-4c67de43-cee2-4331-947e-117e9cbc126c.png)
