### ISSUE TITLE
Styling Audit

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#30]
All examples were previously using their own style sheet. This was ok, but it would be better if they shared a stylesheet and thus had **consistent** styles. 

Create a new style sheet in the root of the project that can be used for ALL different types of interactive learning assessments.

Note that since this story touches many different files, it should be done when there are no open pull requests and be sure to communicate with the team so we don't create any unnecessary conflicts.

**Comment by Raunaq27** [comment]
[Color picker](https://imagecolorpicker.com/color-code/00ff8e)



![Image](https://user-images.githubusercontent.com/121897309/233154911-62c93aa7-87b7-4f99-8a7b-8413f3c7dde1.png)
![Image](https://user-images.githubusercontent.com/121897309/233154910-b4d5b48b-f557-4d08-8c55-60277dfe4e70.png)

I was thinking we could use this color

**Comment by FeXd** [comment]
Color looks good, we use CSS Variables we could easily change it later as well: https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties

**Comment by FeXd** [comment]
Some inspiration from Google Forms: https://docs.google.com/forms/d/e/1FAIpQLScjoZ7DfL1jZizo_V3CtQ35qbSXMhnmie3wGjpE1k0liZYgcw/viewform?usp=sf_link


![Image](https://user-images.githubusercontent.com/553767/234049161-3230e9d8-198d-4347-872c-35b37dca0bcb.png)

Consider updating form styling to be more similar with rounded corners?

**Comment by Raunaq27** [comment]
**Made a wireframe for the styling**


![Image](https://user-images.githubusercontent.com/121897309/234156465-e3b89359-194b-401d-b205-749ce6153477.png)

**Comment by FeXd** [comment]
Generally looks good but I would not abbreviate "Question" just use the full word. Might be cleaner to have background be colored and boxes be white like the example. May be hard to read on green. But otherwise, an improvement.

**Comment by Raunaq27** [comment]
![Image](https://user-images.githubusercontent.com/121897309/234363507-7f6f88bb-ee82-4dfb-83b4-bb3b0511867a.png)

**Comment by FeXd** [comment]
A bit of an improvement, but I'd like to see changes:

- options and questions should also be inside of those round containers.
- header and footer are also square while the description is rounded - be **consistent**
- the green is too intense, dial it back a bit

**Comment by FeXd** [comment]
@Raunaq27 previewed his work today:



![Image](https://user-images.githubusercontent.com/553767/234621345-d86b2276-a64d-4427-9827-14598bc6d86a.png)



Feedback:
- add more side padding to buttons (typically double the top / bottom)
- move the `Copy Code to Clipboard` outside of `<pre>`
- wrap `<pre>` and `<button>` inside an element (maybe `<aside>` or `<section>`) ensure that it has rounded corners consistent with other sections
- added questions and answers are missing the "Type the question here" placeholder
- add more padding to paragraph description at the top
- add padding to `<body>` maybe `1em` or so

**Comment by Raunaq27** [comment]
![Image](https://user-images.githubusercontent.com/121897309/234649409-0967d300-8657-403a-a9a2-83f857633825.png)

**Comment by Raunaq27** [comment]
![Image](https://user-images.githubusercontent.com/121897309/234650291-b79b6c57-8614-4775-8b9f-aaff2d6ff7a2.png)

**Comment by Raunaq27** [comment]
This is how the form looks
