### ISSUE TITLE
Flash Card Activity

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#32]
Create a simple webpage using basic HTML, CSS, and JavaScript, that allows us to have a "Flash Card" activity. Update the interactive learning code generator to support this new activity. Ensure that styling is consistent with other activites.

Example of existing activities are available in /source directory, specifically:

- Interactive Flash Card Activity Template

Please refer to #1 and #2 for more examples.

## Implementation
- please make your files inside a folder directly in the root of the project, for example `expandable-content`
- inside should only be three files, `index.html`, `main.js`, `style.css`
- we are trying to create these examples as simply as possible, with **vanilla JavaScript** where possible (no 3rd party libraries)
- it is possible that a 3rd party library _may_ be required, but please check in before you attempt to implement
- feel free to use the /source examples as a base for your implementation, **but** we **do not** want to be using `jquery`

## Expectations
- there is no specific deadline for this task
- it is expected that you will check in daily on progress
- you should make a new branch on git and **push your branch regularly**
- when you are done, or when you want feedback, please open a pull request and let the team know

**Comment by Anmol135** [comment]
Just got started on the flash card quiz. To check out my progress on the quiz visit my branch [anmol_flash_card](https://github.com/Interactive-Design-and-Technology/interactive-learning/tree/anmol_flash_card)

**Comment by Anmol135** [comment]
Since the examples provided are helpful, I am putting a screenshot of the example.

![Image](https://user-images.githubusercontent.com/121471316/233459446-fd85f2fd-d787-4c9d-94a0-370d164b17ae.png)

**Comment by Anmol135** [comment]
Some Great Flipping Card Examples.[Flip Card](https://www.codehim.com/demo/card-flip-animation-using-javascript-code/)

**Comment by FeXd** [comment]
A pull request has been opened #38
