### ISSUE TITLE
Make a discord server

### ISSUE THREAD

**Issue by Raunaq27** [Interactive-Design-and-Technology/interactive-learning#5]
As discussed on march 24,  Make a discord server so that we can have back and forth communication

**Comment by FeXd** [comment]
@Raunaq27 Be sure to leave comments on cards to update their status.

Discord server was created shortly after meeting by @Raunaq27 and both @Anmol135 & @FeXd have been invited.

**Comment by Raunaq27** [comment]
Added a stand ups channel to discord
