### ISSUE TITLE
Meeting March 31st

### ISSUE THREAD

**Issue by FeXd** [Interactive-Design-and-Technology/interactive-learning#7]
Followup from #6 - plan is too meet at 11:00 AM, Arlin to send invite.

Agenda
- Collect all information from #1 and #2 
- make plan for next week

If there is anything else you'd like to talk about, please comment below.

**Comment by FeXd** [comment]
Some more things to talk about today:

- standups

**Comment by Anmol135** [comment]
Just want to get an idea about what ideas can be actually executable in javascript and what cannot. Like, How high I should be aiming?

**Comment by FeXd** [comment]
@Anmol135 Aim for the moon! Really tho, aim low, then we can improve as we go. Keep in mind the concept [MVP](https://en.wikipedia.org/wiki/Minimum_viable_product).

**Comment by FeXd** [comment]
Takeaways from the meeting:

- @FeXd  will archive assets from #1 and #2 for future reference
- @Raunaq27 @Anmol135 will each pull new cards form Todo, and start coding again!
- Going forward, next week we will have a **daily** meeting at 9:00 AM @FeXd to send out invites
